name: facetomini
description: A new Flutter project.
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  device_preview: ^1.1.0    
  intl: any    
  get_it: ^7.6.0    
  go_router: ^9.0.3
  provider: ^6.0.5
  # Database
  path_provider: ^2.0.15
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.15
  drift: ^2.10.0  
  # Permission
  permission_handler: ^10.4.3
  url_launcher: ^6.1.12
  dio: ^5.3.0
  fl_chart: ^0.40.0
  connectivity_plus: ^4.0.2
  # audio_in_app: ^1.0.1
  # audioplayers: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any 
  drift_dev: ^2.9.0  

flutter:
  uses-material-design: true
  generate: true
  

  assets:
    - asset/app/
    - asset/app/sound/
    - asset/app/error/
    - asset/spin/
    - asset/scenes/
    - asset/winner/
    - asset/series/s_41/373.webp
    - asset/series/s_41/300/373.webp
    - asset/series/s_41/301/374.webp
    - asset/series/s_41/302/375.webp
    - asset/series/s_41/303/376.webp
    - asset/series/s_41/304/377.webp
    - asset/series/s_41/305/378.webp
    - asset/series/s_41/306/379.webp
    - asset/series/s_41/307/380.webp
    # series 2
    - asset/series/s_37/343.webp
    - asset/series/s_37/270/343.webp
    - asset/series/s_37/271/344.webp
    - asset/series/s_37/272/345.webp
    - asset/series/s_37/273/346.webp
    - asset/series/s_37/274/347.webp
    - asset/series/s_37/275/348.webp
    - asset/series/s_37/276/349.webp
    - asset/series/s_37/277/350.webp
    # series 3
    - asset/series/s_29/284.webp
    - asset/series/s_29/181/284.webp
    - asset/series/s_29/182/285.webp
    - asset/series/s_29/183/286.webp
    - asset/series/s_29/184/287.webp
    - asset/series/s_29/185/288.webp
    - asset/series/s_29/186/289.webp
    - asset/series/s_29/187/290.webp
    # series 4
    - asset/series/s_1/11.webp
    - asset/series/s_1/1/11.webp
    - asset/series/s_1/2/12.webp
    - asset/series/s_1/3/13.webp
    - asset/series/s_1/4/14.webp
    - asset/series/s_1/5/15.webp
    # series 5
    - asset/series/s_2/16.webp
    - asset/series/s_2/6/16.webp
    - asset/series/s_2/7/17.webp
    - asset/series/s_2/8/18.webp
    - asset/series/s_2/9/19.webp
    - asset/series/s_2/10/20.webp
    
  fonts:
    - family: Comfortaa
      fonts:
        - asset: asset/app/fonts/text/comfortaa-medium.ttf
    - family: IconsApp
      fonts:
        - asset: asset/app/fonts/icons/faceto.ttf